### ISSUE TITLE
[Error] There is error when thread is running in Pyqt

### ISSUE THREAD

**Issue by kdh0324** [SangbumChoi/Project1_SWZZAZZ#7]
Summary of Bug
- There is error (exit code -1073740771 (0xC000041D)).
- This error code is about thread.
- There isn't error when run the code about video streaming with the webcam alone. But when run our code, the error occurs.

How to occur Bug
1. Record(Open the video)
2. Quit the Record
3. Repeat 1~2 several times

**Comment by SangbumChoi** [comment]
It is quite off topic, but there is a bug when loading several videos in the videolist. Specific bug is about playing button issue when 2 or more video is loaded
